name: jmod Build

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

env:
  LIN64_DIST_DIR: "linux-x64-jmod"
  LINARM64_DIST_DIR: "linux-arm64-jmod"
  WIN64_DIST_DIR: "windows-x64-jmod"
  WIN32_DIST_DIR: "windows-i386-jmod"
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  x86_build_jmod:
    runs-on: [ubuntu-latest]
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v3
        with:
          repository: darkshade9/aq2-jmod
          ref: ${{ github.ref }}
          path: build

      - name: Set shortversion
        id: shortversion
        working-directory: build
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # - name: Download mingw package
      #   working-directory: build
      #   run: |
      #     wget -nv https://github.com/skullernet/q2pro-mgw-sdk/releases/download/2022-06-14/q2pro-mgw-sdk.tar.gz
      #     tar xf q2pro-mgw-sdk.tar.gz

      # - name: Build JMOD (Win 64-bit)
      #   working-directory: build/src
      #   run: make -j4 V=1 && mv gamex86_64.dll ../gamex86_64.dll
      #   env:
      #     CC: x86_64-w64-mingw32-gcc

      # - name: Generate Win64 archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: jmod-win-64
      #     path: |
      #       build/gamex86_64.dll

      # - name: Build JMOD (Win 32-bit)
      #   working-directory: build/src
      #   run: make clean && make -j4 V=1 && mv gamex86.dll ../gamex86.dll
      #   env:
      #     CC: x86_64-w64-mingw32-gcc-win32

      # - name: Generate Win32 archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: jmod-win-32
      #     path: |
      #       build/gamex86.dll

      - name: Build JMOD (Linux 64-bit)
        working-directory: build/src
        run: make clean && make -j4 V=1 && mv gamex86_64.so ../gamex86_64.so
        env:
          CC: "gcc"
          USE_AQTION: "TRUE"

      - name: Generate Linux x86 archive
        uses: actions/upload-artifact@v3
        with:
          name: jmod-lin-x86_64
          path: |
            build/gamex86_64.so

  # arm64_build_jmod:
  #   runs-on: [self-hosted, ARM64]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         repository: darkshade9/aq2-jmod
  #         ref: ${{ github.ref }}
  #         path: build

  #     - name: Build JMOD (Linux ARM64)
  #       working-directory: build/src
  #       run: make -j4 V=1 && mv gameaarch64.so ../gameaarch64.so
  #       env:
  #         CC: "gcc"

  #     - name: Generate archive
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: jmod-lin-arm64
  #         path: |
  #           build/gameaarch64.so

  darwin_build_jmod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: darkshade9/aq2-jmod
          ref: ${{ github.ref }}
          path: build

      - name: Build JMOD (Darwin x86_64)
        working-directory: build/src
        run: make -j4 V=1 && mv gamex86_64.so ../gamex86_64.so
        env:
          CC: "gcc"

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: jmod-darwin-x86_64
          path: |
            build/gamex86_64.so

      # - name: Build JMOD (Darwin ARM64)
      #   working-directory: build/src
      #   run: make clean && make -j4 V=1 && mv gamearm.so ../gamearm64.so

      # - name: Generate archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: jmod-darwin-arm64
      #     path: |
      #       build/gamearm64.so
